--- # jsp viewResolver
spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

--- # ojdbc connection
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: admin
    url: jdbc:oracle:thin:@ocikopodb_medium?TNS_ADMIN=/Users/kantae/Desktop/koreasoftware/Wallet_OCIKOPODB
    password: '@oraclepass12A'

--- # mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: 'true'
